### ISSUE TITLE
Make Fixture

### ISSUE THREAD

**Issue by AxelE** [Mapsred/TicketingBundle#44]
We should make some Fixture for User /  Ticket etc..

When you come at "My tickets" page for example we have some error : 
![image](https://user-images.githubusercontent.com/12477727/41560400-3959a974-7347-11e8-9efd-967041163256.png)

The fixture could fix the problem and will boost the project.

**Comment by Mapsred** [comment]
We need to make fixtures to provide priority as well
Ex :
* Low
* Medium
* High
* Critical

**Comment by Mapsred** [comment]
Example of fixtures : 
* TicketStatus
  * open
  * closed
  * pending
  * in_progress
* TicketPriority
  * low
  * medium
  * high
  * critical
* TicketCategory
  * Question
  * Problem
  * Bug
  * Suggestion

**Comment by AxelE** [comment]
In relation with https://github.com/Mapsred/TicketingBundleDemo/issues/13
