### ISSUE TITLE
Add status history

### ISSUE THREAD

**Issue by lbassin** [Mapsred/TicketingBundle#75]
**Is your feature request related to a problem? Please describe.**
In my opinion, it would be great to see the status history of a ticket in order to quickly see why it take too long to be closed 

**Describe the solution you'd like**
Maybe in the details page (http://ticketing-bundle-demo.mindgame.ovh/ticket/detail/2) you may add a new block "History" below "Commentaires"

**Comment by Mapsred** [comment]
Hi !
Thank you for your suggestion.
I will see to implement it as soon as possible
