### ISSUE TITLE
missing support for english users

### ISSUE THREAD

**Issue by tarlepp** [Mapsred/TicketingBundle#88]
**Is your feature request related to a problem? Please describe.**
Now eg. demo is not showing any english texts, so quite hard to know what to click etc.

**Describe the solution you'd like**
Make your application default language english, so that more people can see / understand what it's doing.

**Describe alternatives you've considered**
Or at least provide some language options that users can choose.

**Additional context**
Didn't found login screen after three different clicks because of that - didn't bother continue further because of this language issue.

**Comment by Mapsred** [comment]
Hi thank you for your feedback

The english translation is partly available in the bundle, but not yet in the demo.

We will finish it very soon
