### ISSUE TITLE
Recipe for SF4.x

### ISSUE THREAD

**Issue by tarlepp** [Mapsred/TicketingBundle#89]
**Is your feature request related to a problem? Please describe.**
Seems like documentation is showing how to setup this bundle as in SF3.x So no really support for SF4.x + flex with recipes to configure this bundle automatically.

**Describe the solution you'd like**
Add recipe for symfony flex to configure this automatically and fix your docs for SF3 and SF4 users.

**Comment by Mapsred** [comment]
Hi
Thank you for your feedback !

We have a recipe since some days now : https://github.com/symfony/recipes-contrib/pull/412
The doc update is in progress and will be release as soon as possible
